src/src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $running_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $director;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $plot;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_url;

    /**
     * @ORM\ManyToMany(targetEntity=Actor::class, inversedBy="films")
     */
    private $actors;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    public function __construct()
    {
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getRunningTime(): ?int
    {
        return $this->running_time;
    }

    public function setRunningTime(int $running_time): self
    {
        $this->running_time = $running_time;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function __toString()
    {
        return "Title: $this->title; Director: $this->director; Genre: $this->genre; Running Time: $this->running_time";
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getPlot(): ?string
    {
        return $this->plot;
    }

    public function setPlot(?string $plot): self
    {
        $this->plot = $plot;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        $this->actors->removeElement($actor);

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('running_time', NumberType::class, [
                'empty_data' => 0,
                'html5' => true,
            ])
            ->add('poster_url', FileType::class, [
                'required' => false,
                'mapped' => false,
                'data_class' => null,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => ['image/jpeg', 'image/png', 'image/gif'],
                        'mimeTypesMessage' => 'The allowed mime types are jpeg, png and gif.'
                    ])
                ],
            ])
            ->add('director')
            ->add('genre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Actor;
use App\Entity\Film;
use App\Form\AddActorFormType;
use App\Form\SearchFilmType;
use App\Repository\ActorRepository;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FilmService;
use App\Service\SimpleSearchService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;

#[Route('/film')]
class FilmController extends AbstractController
{

    #[Route('/list', name: 'film_index', methods: ['GET'])]
    public function index(FilmRepository $filmRepository, Request $request): Response
    {
        $page = $request->query->has('page') ? $request->query->get('page') : 1;
        return $this->render('film/index.html.twig', [
            'films' => $filmRepository->findAllPaginated($page),
            'pagination' => $filmRepository->getPagination(),
        ]);
    }

    #[Route('/show/{id}', name: 'film_show', methods: ['GET'])]
    public function show(Film $film): Response
    {
        return $this->render('film/show.html.twig', [
            'film' => $film,
        ]);
    }

    #[Route('/{id}/add/actor', name: 'film_add_actor', methods: ['POST'])]
    public function addActor(
        Request $request,
        Film $film,
        EntityManagerInterface $entityManager,
        LoggerInterface $appInfoLogger
    ): Response
    {
        $this->denyAccessUnlessGranted('edit', $film);
        $addActorForm = $this->createForm(AddActorFormType::class);
        $addActorForm->handleRequest($request);
        $actor = $addActorForm->getData()['actor'];
        $film->addActor($actor);
        $appInfoLogger->info($this->getUser()->getEmail() . " added actor " .$actor->getName(). " to film " . $film->getTitle());
        $entityManager->flush();
        $this->addFlash('success', 'The actor had been added.');
        return $this->redirectToRoute('film_edit', [
            'id' => $film->getId(),
        ]);
    }
    #[Route('/{id}/delete/actor/{id_actor}', name: 'film_delete_actor', methods: ['POST'])]
    public function deleteActor(
        Request $request,
        Film $film,
        EntityManagerInterface $entityManager,
        LoggerInterface $appInfoLogger,
        ActorRepository $actorRepository,
        $id_actor
    ): Response
    {
        $this->denyAccessUnlessGranted('edit', $film);
        $actor = $actorRepository->find($id_actor);
        $film->removeActor($actor);
        $appInfoLogger->info($this->getUser()->getEmail() . " added actor " .$actor->getName(). " to film " . $film->getTitle());
        $entityManager->flush();
        $this->addFlash('success', 'The actor had been deleted.');
        return $this->redirectToRoute('film_edit', [
            'id' => $film->getId(),
        ]);
    }


    #[Route('/search', name: 'film_search', methods: ['GET', 'POST'])]
    public function searchFilms(Request $request, FilmRepository $filmRepository, SimpleSearchService $simpleSearchService)
    {
        $form = $this->createForm(SearchFilmType::class, null, [
            'field_choices' => [
                'Title' => 'title',
                'Director' => 'director',
                'Genre' => 'genre'
            ],
            'order_choices' => [
                'Genre' => 'genre',
                'Running Time' => 'running_time',
                'Year' => 'year',
            ],
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $films = $simpleSearchService->search(Film::class, $data);
        } else {
            $films = $filmRepository->findAll();
        }

        return $this->render('film/film_search.html.twig', [
            'films' => $films,
            'search_form' => $form->createView(),
        ]);
    }

    #[Route('/new', name: 'film_new', methods: ['GET','POST'])]
    public function new(Request $request, FilmService $filmService, LoggerInterface $appInfoLogger): Response
    {
        $film = $filmService->createNewFilm($request, $this->getUser());

        $this->denyAccessUnlessGranted('create', $film);

        if ($film->getId()) {

            $this->addFlash(
                'success',
                "Film " . $film->getTitle() . " was created!"
            );
            $appInfoLogger->info($this->getUser()->getEmail() . " create film " . $film->getTitle());
            return $this->redirectToRoute('film_show', [
                'id' => $film->getId(),
            ], Response::HTTP_SEE_OTHER);

        }

        return $this->renderForm('film/new.html.twig', [
            'film' => $film,
            'form' => $filmService->getFilmForm()
        ]);
    }

    #[Route('/{id}/edit', name: 'film_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Film $film, FilmService $filmService, LoggerInterface $appInfoLogger): Response
    {
        $this->denyAccessUnlessGranted('edit', $film);
        $form = $filmService->createFilmForm($request, $film);

        $ids = [];
        foreach ($film->getActors() as $actor) {
            $ids[] = $actor->getId();
        }

        $addActorForm = $this->createForm(AddActorFormType::class, null, [
                'action' => $this->generateUrl('film_add_actor', [
                            'id' => $film->getId(),
                ]),
                'ids' => $ids,
            ]);

        if ($form->isSubmitted() && $form->isValid()) {
            $film = $filmService->updateFilm($request, $film);
            $appInfoLogger->info($this->getUser()->getEmail() . " edit film " . $film->getTitle());
            return $this->redirectToRoute('film_show', [
                'id' => $film->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/edit.html.twig', [
            'film' => $film,
            'addActorForm' => $addActorForm,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'film_delete', methods: ['POST'])]
    public function delete(Request $request, Film $film, FilmService $filmService, LoggerInterface $appInfoLogger): Response
    {
        $this->denyAccessUnlessGranted('delete', $film);
        if ($this->isCsrfTokenValid('delete'.$film->getId(), $request->request->get('_token'))) {
            $appInfoLogger->info($this->getUser()->getEmail() . " delete film " . $film->getTitle());
            $filmService->deleteFilm($film);
        }

        return $this->redirectToRoute('film_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/templates/film/_delete_actor.html.twig
<form method="post" action="{{ path('film_delete_actor', {
    id: film.id,
    id_actor: actor.id
    }) }}" onsubmit="return confirm('Are you sure you want to delete this actor?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn btn-outline-danger float-end">
        <i class="bi bi-trash"></i>
    </button>
</form>

src/templates/film/_delete_form.html.twig
<form method="post" action="{{ path('film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

src/templates/film/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
{% if addActorForm is defined %}
    <div class="row p-2 my-3">
        <div class="col-3">
            <label>Actors</label>
            <ul class="list-group p-2 my-2">
                {% for actor in film.actors %}
                    <li class="list-group-item p-2">
                        {{ actor.name }}
                        {% include "film/_delete_actor.html.twig" %}
                    </li>
                {% else %}
                    <li class="list-group-item warning">No actors added yet.</li>
                {% endfor %}
            </ul>
        </div>
            <div class="col-3">
                {{ form_start(addActorForm) }}
                    {{ form_widget(addActorForm) }}
                {{ form_end(addActorForm) }}
            </div>
    </div>
{% endif %}

src/templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-outline-secondary" href="{{ path('film_index') }}">back to list</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

src/templates/film/film_card.html.twig
<div class="col d-flex justify-content-between align-items-center">
    <div class="card shadow-sm">
        {% if film.posterUrl matches '{https://}' %}
            <img src="{{film.posterUrl}}" class="thumbnail img-responsive">
        {% else %}
            <img src="{{ asset(covers_dir ~'/'~(film.posterUrl ?? 'default.jpg'))}}" class="thumbnail img-responsive">
        {% endif %}
        <div class="card-body">
            <h4>{{ film.title }}</h4>
            <h6 class="text-muted">{{ film.genre }}</h6>
            <div class="d-flex justify-content-between align-items-center">
                
                <div class="btn-group">
                    <a href="{{ path('film_show', {'id': film.id}) }}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                    {% if is_granted('edit', film) %}
                        <a href="{{ path('film_edit', {'id': film.id}) }}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    {% endif %}
                </div>
                <small class="text-muted">{{ film.runningTime }} mins</small>
            </div>
        </div>
    </div>
</div>

src/templates/film/film_search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search in films{% endblock %}

{% block body %}
    <h1>Search in films</h1>
    {{ form_start(search_form) }}
            <div class="row mb-3 p-3 bg-secondary rounded">
                <div class="col-2">
                    {{ form_row(search_form.field) }}
                </div>
                <div class="col-2">
                    {{ form_row(search_form.value) }}
                </div>
                <div class="col-2">
                    {{ form_row(search_form.order) }}
                </div>
                <div class="col-2">
                    {{ form_row(search_form.direction) }}
                </div>
                <div class="col-2">
                    {{ form_row(search_form.limit) }}
                </div>
                <div class="col-2">
                    <div style="margin: 20%">
                        {{ form_row(search_form.Search) }}
                    </div>
                </div>
            </div>

    {{ form_end(search_form) }}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for film in films %}
            {% include "film/film_card.html.twig" %}
        {% endfor %}
    </div>
{% endblock %}

src/templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of films{% endblock %}

{% block body %}
    <h1>List of Films</h1>
    <div class="row">
        <a class="m-3 col-2 btn btn-outline-primary" href="{{ path('film_search') }}">Search</a>
        {% if is_granted('ROLE_USER') %}
            <a class="m-3 col-2 btn btn-outline-primary" href="{{ path('film_new') }}">New Film</a>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for film in films %}
            {% include "film/film_card.html.twig" %}
        {% endfor %}
    </div>
    {% include('paginator.html.twig') %}
{% endblock %}

src/templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film{% endblock %}

{% block body %}
    <h1>Create new Film</h1>

    {{ include('film/_form.html.twig') }}

    <a class="btn btn-outline-secondary" href="{{ path('film_index') }}">back to list</a>
{% endblock %}

src/templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ film.title }}{% endblock %}

{% block body %}
    <h1>{{ film.title }}</h1>
    <div class="row">
        <div class="col-3">
            {% if film.posterUrl matches '{https://}' %}
                <img src="{{film.posterUrl}}" class="rounded img-fluid">
            {% else %}
                <img src="{{ asset(covers_dir ~'/'~(film.posterUrl ?? 'default.jpg'))}}" class="rounded img-fluid">
            {% endif %}
            <a class="btn btn-outline-secondary my-3" href="{{ path('film_index') }}">back to list</a>
            {% if is_granted('edit', film) %}
                <a class="btn btn-outline-warning" href="{{ path('film_edit', {'id': film.id}) }}">edit</a>
            {% endif %}
            {% if is_granted('edit', film) %}
                {{ include('film/_delete_form.html.twig') }}
            {% endif %}
        </div>
        <div class="col-9">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Year</th>
                        <td>{{ film.year }}</td>
                    </tr>
                    <tr>
                        <th>Title</th>
                        <td>{{ film.title }}</td>
                    </tr>
                    <tr>
                        <th>Running Time</th>
                        <td>{{ film.runningTime }} min.</td>
                    </tr>
                    <tr>
                        <th>Director</th>
                        <td>{{ film.director }}</td>
                    </tr>
                    <tr>
                        <th>Genre</th>
                        <td>{{ film.genre }}</td>
                    </tr>
                    <tr>
                        <th>Plot</th>
                        <td>{{ film.plot }}</td>
                    </tr>
                </tbody>
            </table>
            <h5>Actors</h5>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 mb-4">
                {% for actor in film.actors %}
                    {% include "actor/actor_card.html.twig" %}
                {% else %}
                    <ul class="list-group p-2 my-3">
                        <li class="list-group-item warning">No actors added yet.</li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}